# WEB


## cve-2024-28397-remote.py

I faced this cve while trying to solve a ctf, i had to adapt the code in order to be used remotely. The initial PoC was created for a local use.

Original CVE disclosed by [Marven11](https://github.com/Marven11/CVE-2024-28397-js2py-Sandbox-Escape)
